# Gunakan image Go
FROM golang:1.21 AS builder

WORKDIR /app

# Copy go.mod dan go.sum dulu
COPY go.mod go.sum ./
RUN go mod download

# Copy semua source code
COPY . .

# Build binary dari cmd/server/main.go
RUN go build -o main ./cmd/server/main.go

# Stage kedua: image lebih kecil
FROM debian:bookworm-slim

WORKDIR /app

# Copy binary dari stage builder
COPY --from=builder /app/main .

# Expose port (sesuaikan dengan port app kamu, misalnya 8080)
EXPOSE 8080

# Jalankan binary
CMD ["./main"]
